{% set name = "vdom" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 953d33c0b5cc6e7fec57b350c18bfd31b40439b88671661b6f86f77a42a5aeab

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - ipython
    - jsonschema
    - python

test:
  imports:
    - vdom

about:
  home: https://github.com/nteract/vdom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: VDOM for Python
  dev_url: https://github.com/nteract/vdom

extra:
  recipe-maintainers:
    - gnestor
