travis:
  secure:
    BINSTAR_TOKEN: Fv60o1hHowvyehYxUxkcMcIdRuNY7mlgTpVKOzy93Bp3bP1LU1iYgewLBkHuv2QjdEzBnd1kvdwyXtZmZ9V67KwPuZDWRwwVsLZpNFfZli8Dg7ecqTL6HhjYoWBoWbCWVAtC6jEwAuKcx69qLvBEalQCgJAmZMuYBJcaoOMJ08jinPabfg5B2kxQqd+bib/iKQfGu5dvN1NZF+NifpN4MFE2YmsQ+a282fR0oNG1rbUX7aZhTKUytOo8/h8XwDrhBDEudPq5jkBL6HB1QZKr7FS38QL94l+YssT/ccjQVNrT6dC0oYT20zX3WgIydgqYxRZILO4h71AgeSAYTF9mFVvJwlIOdeI8VBo68t9NXXisdYk5hHOy4p1h4h6oksdl3TKtQEvp72AK4ohCv6vZJkerpE7BLwzxUBrpHJI3tfZuSnsEqF30uiIjEWOWtbrZp84qvJZItmlzJl6BU3y2xg5oGgqtI60xravqwD2ZvVnwxgDau3NTN6WdlBlB9wRwq7Julv8EvCHd03R22j8sgWZkZnF/FNkPjB4M/DhS8Tw0nZqJTCEGWOvYAPI4edMExMpkMQIBClLx9UDLZpuBs16uc0Y+ANxkWvkcrzY72w5fHw+vPTew/10xFuxlDBJxFvDtVe8OPPiaq2FH2OJzk8u9lvz1mv6jzExdTdxJULM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
